name = "cx"
main = "src/index.js"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "local" }

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production" }